name: print output using context variables
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: build
        id: step1
        run: echo " message=hello my name is bhavya " >> $GITHUB_OUTPUT
      - name: deploy
        run: echo " OUTPUT IS ${{steps.step1.outputs.message}} "
