name: multiple-jobs
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is system information"
      - run: date
      - run: free -h
      - run: du -h
      - run: hostname
      - run: whoami
