name: multiple-jobs
on: workflow_dispatch
jobs:
  job-1:
    runs-on: self-hosted
    steps:
      - name: system-info
        run: |
         echo "this is system information"
         date
         whoami
         uname -a
         free -h
         du -h
