name: dependency workflow
on: push
jobs:
runs-on: ubuntu-latest
  code:
    steps:
      - run: echo "this is our source code"
  build:
    needs: code
    steps:
      - run: echo "this is building stage"
  test:
    needs: build
    steps:
      - run: echo "this is testing stage"
  deploy:
   needs: test
    steps:
      - run: echo "this is deploying ...."
